/**
 * Copyright 2020-2021 University of Oxford and Health and Social Care Information Centre, also known as NHS Digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 04:44:22 PM GMT 
//


package uk.ac.ox.softeng.maurodatamapper.plugins.xsd.org.w3.xmlschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType$gt;
 *   &lt;complexContent$gt;
 *     &lt;extension base="{http://www.w3.org/2001/XMLSchema}openAttrs"$gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"$gt;
 *         &lt;element ref="{http://www.w3.org/2001/XMLSchema}annotation"/$gt;
 *         &lt;group ref="{http://www.w3.org/2001/XMLSchema}redefinable"/$gt;
 *       &lt;/choice$gt;
 *       &lt;attribute name="schemaLocation" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /$gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /$gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/$gt;
 *     &lt;/extension$gt;
 *   &lt;/complexContent$gt;
 * &lt;/complexType$gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotationsAndSimpleTypesAndComplexTypes"
})
@XmlRootElement(name = "redefine")
public class Redefine
    extends OpenAttrs {

    @XmlElements({
                     @XmlElement(name = "annotation", type = Annotation.class),
                     @XmlElement(name = "simpleType", type = SimpleType.class),
                     @XmlElement(name = "complexType", type = ComplexType.class),
                     @XmlElement(name = "group", type = Group.class),
                     @XmlElement(name = "attributeGroup", type = AttributeGroup.class)
                 })
    protected List<OpenAttrs> annotationsAndSimpleTypesAndComplexTypes;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "schemaLocation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String schemaLocation;

    /**
     * Gets the value of the annotationsAndSimpleTypesAndComplexTypes property.
     *
     * <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the annotationsAndSimpleTypesAndComplexTypes property.
     *
     * <p> For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationsAndSimpleTypesAndComplexTypes().add(newItem);
     * </pre>
     *
     *
     * <p> Objects of the following type(s) are allowed in the list {@link Annotation } {@link SimpleType } {@link ComplexType } {@link Group } {@link
     * AttributeGroup }
     */
    public List<OpenAttrs> getAnnotationsAndSimpleTypesAndComplexTypes() {
        if (annotationsAndSimpleTypesAndComplexTypes == null) {
            annotationsAndSimpleTypesAndComplexTypes = new ArrayList<OpenAttrs>();
        }
        return this.annotationsAndSimpleTypesAndComplexTypes;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the schemaLocation property.
     *
     * @return possible object is {@link String }
     */
    public String getSchemaLocation() {
        return schemaLocation;
    }

    /**
     * Sets the value of the schemaLocation property.
     *
     * @param value allowed object is {@link String }
     */
    public void setSchemaLocation(String value) {
        this.schemaLocation = value;
    }

}
