//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 04:44:22 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/XMLSchema",
                                     elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
                                     xmlns = {@XmlNs(prefix = "xs", namespaceURI = "http://www.w3.org/2001/XMLSchema")})
package ox.softeng.metadatacatalogue.plugins.xsd.org.w3.xmlschema;

import javax.xml.bind.annotation.XmlNs;